include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    unawaited_futures: true
    always_use_package_imports: false
    prefer_relative_imports: true
    specify_nonobvious_property_types: false
    one_member_abstracts: false
    sort_unnamed_constructors_first: true
    sort_constructors_first: false
    discarded_futures: true
    prefer_expression_function_bodies: true
