include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    unawaited_futures: true
    always_use_package_imports: false
    prefer_relative_imports: true
    specify_nonobvious_property_types: false
