name: Task
description: Техническая задача
title: "Task: "
labels: ["type: task"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Цель
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Компонент
      options:
        - Mobile
        - Backend
        - DevOps
        - Design
        - Docs
  - type: input
    id: estimate
    attributes:
      label: Оценка (SP или часы)
      placeholder: например 2
  - type: textarea
    id: steps
    attributes:
      label: Шаги/подзадачи
      value: |
        - [ ] …
