name: User Story
description: Пользовательская история
title: "Story: "
labels: ["type: story"]
body:
  - type: input
    id: as_a
    attributes:
      label: Как
      placeholder: пользователь/владелец кабинета/админ…
    validations:
      required: true
  - type: input
    id: i_want
    attributes:
      label: Я хочу
      placeholder: действие/функция
    validations:
      required: true
  - type: input
    id: so_that
    attributes:
      label: Чтобы
      placeholder: причина/ценность
  - type: dropdown
    id: component
    attributes:
      label: Компонент
      options:
        - Mobile
        - Backend
        - DevOps
        - Design
        - Docs
  - type: input
    id: estimate
    attributes:
      label: Оценка (Story Points)
      placeholder: число, например 3
  - type: textarea
    id: acceptance
    attributes:
      label: Критерии приемки
      description: Желательно в формате Given-When-Then
      value: |
        - [ ] Given …
        - [ ] When …
        - [ ] Then …
  - type: textarea
    id: dependencies
    attributes:
      label: Зависимости/блокеры
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
      value: |
        - [ ] Реализовано
        - [ ] Тесты/ручная проверка
        - [ ] Документация/Swagger обновлены
        - [ ] Ревью и merge PR
